/** Runtime gates for Phase 2 capabilities. */

export const CONTROL_CAPABILITIES = {
  USER_HELP: "CONTROL_CAP_USER_HELP",
  HUB_DISCOVERY: "CONTROL_CAP_HUB_DISCOVERY",
  HUB_UPVOTE: "CONTROL_CAP_HUB_UPVOTE",
  USER_PROFILE: "CONTROL_CAP_USER_PROFILE",
  USER_ACTIVITY: "CONTROL_CAP_USER_ACTIVITY",
  USER_PREFERENCES: "CONTROL_CAP_USER_PREFERENCES",
  USER_INBOX: "CONTROL_CAP_USER_INBOX",
  USER_FEEDBACK: "CONTROL_CAP_USER_FEEDBACK",
  HUB_LIST: "CONTROL_CAP_HUB_LIST",
  MODERATION: "CONTROL_CAP_MODERATION",
  HUB_LIFECYCLE: "CONTROL_CAP_HUB_LIFECYCLE",
  HUB_CONFIG: "CONTROL_CAP_HUB_CONFIG",
  HUB_RULES: "CONTROL_CAP_HUB_RULES",
  HUB_INVITES: "CONTROL_CAP_HUB_INVITES",
  HUB_TEAM: "CONTROL_CAP_HUB_TEAM",
  HUB_ANNOUNCEMENTS: "CONTROL_CAP_HUB_ANNOUNCEMENTS",
  HUB_BADGES: "CONTROL_CAP_HUB_BADGES",
  HUB_LOGGING: "CONTROL_CAP_HUB_LOGGING",
  HUB_AUDIT: "CONTROL_CAP_HUB_AUDIT",
  SERVER_CONFIG: "CONTROL_CAP_SERVER_CONFIG",
  SERVER_BLOCKLIST: "CONTROL_CAP_SERVER_BLOCKLIST",
  CONNECTIONS: "CONTROL_CAP_CONNECTIONS",
} as const;

export type ControlCapability = keyof typeof CONTROL_CAPABILITIES;

export function isCapabilityEnabled(capability: ControlCapability): boolean {
  const value = process.env[CONTROL_CAPABILITIES[capability]]?.trim().toLowerCase();
  return value === "true" || value === "1";
}
